# =============================================================
# CONFIGURATION GENERALE
# =============================================================
spring.application.name=demo

# =============================================================
# CONFIGURATION POSTGRESQL (Base de données persistante)
# VOUS DEVEZ REMPLACER LES VALEURS PAR VOS PROPRES IDENTIFIANTS
# =============================================================

# 1. Connexion à la BDD PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/tontine_db
spring.datasource.username=postgres
spring.datasource.password=manitou66*
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuration JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
# 'update' : Met à jour le schéma (crée les tables si elles n'existent pas)
spring.jpa.hibernate.ddl-auto=update

# 3. Configuration de log (optionnel, pour plus de clarté)
logging.level.org.hibernate.SQL=DEBUG