# Generated by Django 5.1.1 on 2025-06-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercice",
            name="date_fin",
            field=models.DateField(blank=True, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="exercice",
            name="nom",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom de l'exercice"
            ),
        ),
    ]
