# Generated by Django 5.1.1 on 2025-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_exercice_date_fin_alter_exercice_nom"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="exercice",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="exercice",
            name="date_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Date de fin"),
        ),
        migrations.AlterField(
            model_name="exercice",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_COURS", "En cours"),
                    ("TERMINE", "Terminé"),
                    ("PLANIFIE", "Planifié"),
                    ("EN_PREPARATION", "En préparation"),
                ],
                default="EN_COURS",
                max_length=15,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="nom",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom de la session"
            ),
        ),
    ]
