# Generated by Django 5.1.1 on 2025-06-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_exercice_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="statut",
            field=models.CharField(
                choices=[
                    ("EN_COURS", "En cours"),
                    ("TERMINEE", "Terminée"),
                    ("PLANIFIEE", "Planifiée"),
                ],
                default="EN_COURS",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
    ]
