spring.application.name=mutuelle-mobile
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=dev

jwt.secret=MaSuperCleSecreteDe32CaracteresMinimum12345678
jwt.access.expiration=9000000
jwt.refresh.expiration=604800000


#   SMTPAdd commentMore actions
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alongamofranky@gmail.com
spring.mail.password=qhjc neen rwpc kzwq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true

# Activer le debug Thymeleaf
spring.thymeleaf.mode=HTML 
spring.thymeleaf.cache=false 
logging.level.org.springframework.web=DEBUG
