# Generated by Django 5.1.1 on 2025-06-06 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprunt",
            name="date_remboursement_max",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date Remboursement max",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assistanceaccordee",
            name="statut",
            field=models.CharField(
                choices=[
                    ("DEMANDEE", "Demandée"),
                    ("APPROUVEE", "Approuvée"),
                    ("PAYEE", "Payée"),
                    ("REJETEE", "Rejetée"),
                ],
                default="PAYEE",
                max_length=15,
                verbose_name="Statut",
            ),
        ),
    ]
