# Generated by Django 5.1.1 on 2025-06-06 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_session_statut"),
        ("transactions", "0002_emprunt_date_remboursement_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emprunt",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emprunt",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="emprunt",
            name="date_remboursement_max",
            field=models.DateField(
                blank=True,
                help_text="Si non renseignée, sera automatiquement fixée à 2 mois après la date d'emprunt",
                null=True,
                verbose_name="Date de Remboursement maximale",
            ),
        ),
        migrations.AddIndex(
            model_name="emprunt",
            index=models.Index(
                fields=["statut", "date_remboursement_max"],
                name="transaction_statut_09c868_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emprunt",
            index=models.Index(
                fields=["membre", "statut"], name="transaction_membre__abe997_idx"
            ),
        ),
    ]
